### ISSUE TITLE
[Typo] convert the whole codebase to TypeScript

### ISSUE THREAD

**Issue by veej** [buildo/react-components#1034]
## requirements

1. **Every** file in `src` should be refactored in TS
1. the declarations `.d.ts` should be automatically generated from the relative `.tsx?` file
1. keep the `@props` and the `export const Props` to maintain compatibility for projects that are not in TS

## specs

1. pick a component in JS and open a sub-issue called `[Typo] TheComponentYouPicked`
1. copy-paste the types from the `.d.ts` to the new `.tsx?` file
a. **don't** copy the tcomb type export as it's now inferred from TS (`export const Props: { [key: string]: Type<any> };`)
b. improve typings if you think they're not perfect but keep the same structure to avoid breaking changes (`namespace`, ..etc)
b. **remove @skinnable**
1. delete the `.d.ts` files
1. if there are tests
a. rename them in `.tsx`
b. if they test `getLocals` fix them using `enzyme` as done here: [https://github.com/buildo/react-components/pull/1047/files](https://github.com/buildo/react-components/pull/1047/files)
1. before asking for a review please:
a. run `npm test`
b. run `npm start` and check that you component's examples still work with no error in console

NOTE: If you have to add a `@types/x` dependency please add it **without** the `^` as `@types` doesn't follow semver

## misc
{optional: other useful info}

## sub-issues

- [x] add support for TypeScript #1035 **[veej]**
- [x] Icon #1036 
- [x] AsyncStatusIndicator #1040 **[ascariandrea]**
- [x] BackgroundDimmer #1044 **[ascariandrea]**
- [x] Badge #1045
- [x] Browser Detector #1052 
- [x] Button #1053 **[ascariandrea]**
- [x] CollapsibleSection #1056 
- [x] ConfirmationInput #1059 **[veej]**
- [x] DateField #1062 **[veej]**
- [x] DatePicker #1064 **[veej]**
- [x] Divider #1065 **[veej]**
- [x] Dropdown #1066
- [x] DropdownMenu #1067 **[veej]**
- [x] FocusableView #1068 **[ecamellini]**
- [x] FormattedText #1069 **[veej]**
- [x] Image #1070 **[ascariandrea]**
- [x] LoadingSpinner #1072 
- [x] Meter #1073
- [x] Popover #1089
- [x] MobileDetector #1091 **[ascariandrea]**
- [x] Modal #1092
- [x] ResizeSensor #1094
- [x] TransitionWrapper #1097
- [x] TextOverflow #1098
- [x] Overflow #1100 **[FrancescoCioria]**
- [x] MoreOrLess #1101
- [x] Navbar #1103
- [x] Toaster #1108
- [x] Toggle #1110
- [x] Tooltip #1113 **[francescogior]**
- [x] Panel #1123 **[veej]**
- [x] ScrollView #1125 **[veej]**
- [x] TimePicker #1131 **[giogonzo]**
- [x] Tablo #1134
- [x] TextOverflow popover.event type #1139 **[giogonzo]**
- [x] Use TS namespaces for exported types #1083 **[FrancescoCioria]**
