### ISSUE TITLE
standardize code

### ISSUE THREAD

**Issue by FrancescoCioria** [buildo/react-components#204]
## requirements
code on this repo should follow stricter rule so to avoid differences between components (ex: new frontends are not used to `React.createClass({})`)

## sub-issues

- [x] use ES6 classes #207 
- [x] use tcomb + tcomb-react for prop evaluation
- [x] update buildo/eslint-config #205 
- [x] import b-r-c components directly #213
- [x] every folder should be in `kebab-case` #188 **[FrancescoCioria]**

## without issue
- [ ] ~~add docs to every component~~
- [ ] ~~each component should export its `props`~~
- [ ] ~~SASS files should follow our naming convention~~
- [ ] ~~`style`, `className`, `id` to every component~~

**Comment by FrancescoCioria** [comment]
closing in favor of #490
