### ISSUE TITLE
[KitchenSink] Road to shiny stars

### ISSUE THREAD

**Issue by veej** [buildo/react-components#490]
## requirements
Give a better presentation of `buildo-react-components` in order to make them usable outside buildo.

## specs
Actual implementation is not enough shiny to be presented to a future customer. We should have a homogeneous theme and better auto-generated documentation.

## misc
{optional: other useful info}

## sub-issues

- [x] Props documentation #491 **[veej]**
- [x] Examples definition #493 **[ascariandrea]**
- [x] Readme generator #494 **[veej]**
- [x] Component page composition #495 **[veej]**
- [ ] Section pages #496 
- [x] Publish step #497 
- [x] Add CI task to update doc-readmes #507 **[FrancescoCioria]**
- [x] Overall look&amp;feel #519 **[veej]**
- [x] Landing page &amp; guide #522 **[veej]**
- [x] Minor style changes #523 **[veej]**
- [x] Handle external components #528 
- [x] Default style for components #529 **[veej]**
- [x] Various UI fixes #596 **[veej]**

**Comment by FrancescoCioria** [comment]
@veej @ascariandrea some of those issue are duplicate of #204 sub-issues.

Did you take a look at #204?

**Comment by ascariandrea** [comment]
Yep, there are duplicates, but with different specs, I propose to talk about this new step offline.

**Comment by gabro** [comment]
pet peeve, Buildo doesn't exist, buildo does :P
