### ISSUE TITLE
[Examples restyling] 🎨

### ISSUE THREAD

**Issue by FrancescoCioria** [buildo/react-components#566]
## requirements
now that we have a beautiful showroom with beautiful components we should restyle our examples and improve them with better title and descriptions :)

## specs

- restyle examples following alessandra&#39;s mockups
- give meaningful titles/descriptions to every example

## misc
{optional: other useful info}

## sub-issues

- [x] Meter examples #565 **[veej]**
- [x] Dropdown examples restyling #557 **[veej]**
- [x] Add badge example #559 **[veej]**
- [x] NavBar example restyling #555 **[veej]**
- [x] CollapsableSection example restyling #553 **[veej]**
- [x] BackgroundDimmer example restyle #551 **[veej]**
- [x] Panel page and examples #544 **[veej]**
- [x] Button page with examples #541 **[veej]**
- [x] CollapsableSection example style is overriding general style #563 **[veej]**
- [x] DropdownMenu examples #561 **[veej]**
- [x] MoreOrLess example #568 **[veej]**
- [x] ModalManager #570 **[veej]**
- [x] Toaster #572 **[veej]**
- [x] Tooltips #575 **[veej]**
- [x] TextOverflow #582 **[veej]**
- [x] ScrollView #584 **[veej]**
- [x] Popover #586 **[veej]**
- [ ] various minor examples restyling #598 **[veej]**

**Comment by nemobot** [comment]
@FrancescoCioria don't forget to add a topic label (`documentation`)
