### ISSUE TITLE
[Style Linter] Add style linter in workflow

### ISSUE THREAD

**Issue by ascariandrea** [buildo/react-components#614]
## description
We&#39;re evaluating to introduce `stylelint` in our workflow to make style more consistent across the team.

## specs
We picked `stylelint` instead of `csscomb` cause it&#39;s more supported, has a bigger community and its philosophy is equal to `eslint`.

## misc
{optional: other useful info}

## sub-issues

- [x] Define a `.stylelintrc` #615 **[ascariandrea]**
- [x] Add relative webpack loader #616 
- [x] Fix all style files #618 
- [x] Add CI step #619
