### ISSUE TITLE
[tablo perf] - Tablo performances

### ISSUE THREAD

**Issue by francescogior** [buildo/react-components#662]
## requirements
{describe the new feature}

## specs
{optional: describe technical specs to implement this feature, if not obvious}

### TODO
*check opened issues*

- [x] create isolated enviroment (`npm start component`), as simple as possible
- [ ] benchmark with `Table/Grid` (old grid component) (also using `fdt-2` as dep)
- [ ] setup several use cases as tests
- [ ] try `react-addons-perf` (`window.perf = require(&amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;#39;react-addons-perf&amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;amp;#39;)`)
- [ ] [https://paper.dropbox.com/doc/React-Perf-IE-BAoDbq6vDCbJQXAROLVAJ](https://paper.dropbox.com/doc/React-Perf-IE-BAoDbq6vDCbJQXAROLVAJ)

## sub-issues

- [x] Create an isolated environment for testing #667 **[veej]**
- [x] isolated index.html for isolated component #672 **[francescogior]**

**Comment by FrancescoCioria** [comment]
@francescogior @veej can you open the remaining sub-issues?

> require(&amp;amp;amp;amp;amp;amp;amp;#39;react-addons-perf&amp;amp;amp;amp;amp;amp;amp;#39;)

oops, seems like @nemobot 's defect!!!
