### ISSUE TITLE
[Tablo Perf]

### ISSUE THREAD

**Issue by FrancescoCioria** [buildo/react-components#711]
## requirements
as described in [this paper](https://paper.dropbox.com/doc/Tablo-Perf-KndYzIbqC77SJmkzNtV1j) there some perf issues we should solve. Most of them are minor apart from the first one which slows down development considerably.

## specs
split in sub-issues

## misc
{optional: other useful info}

## sub-issues

- [x] disable prop validation for fixed-data-table-2 also in development #712 **[FrancescoCioria]**
- [x] horizontal virtualization should be settable and on by default #713 **[FrancescoCioria]**
- [x] handle hover style for rows in CSS #714 **[FrancescoCioria]**
- [x] onRowMouseEnter/Leave are always passed to fdt2 #715 **[FrancescoCioria]**
