### ISSUE TITLE
[typescript .d.ts] Create .d.ts

### ISSUE THREAD

**Issue by ascariandrea** [buildo/react-components#908]
## requirements
Declare `.d.ts` file with all components' types

## specs
{optional: describe technical specs to implement this feature, if not obvious}

## misc
{optional: other useful info}

## sub-issues

- [x] Divider #909 **[ascariandrea]**
- [x] DropdownMenu #910 **[ascariandrea]**
- [x] Icon #911 **[FrancescoCioria]**
- [x] Panel #912
- [x] ScrollView #913 **[ascariandrea]**
- [x] Tooltip #914 **[ascariandrea]**
- [x] Async Status Indicator #915 **[ascariandrea]**
- [x] BackgroundDimmer #916 
- [x] Badge #917 
- [x] Browser Detector #918 **[ascariandrea]**
- [x] Button #919 **[ascariandrea]**
- [x] CollapsableSection #920 **[ascariandrea]**
- [x] ConfirmationInput #921 **[ascariandrea]**
- [x] Dropdown #922 **[ascariandrea]**
- [x] FocusableView #923 **[FrancescoCioria]**
- [x] FormattedText #924 **[ascariandrea]**
- [x] LinkState #925 **[ascariandrea]**
- [x] LoadingSpinner #926 **[FrancescoCioria]**
- [x] Meter #927 **[ascariandrea]**
- [x] MobileDetector #928 
- [x] ModalManager #929 
- [x] Modal #930 **[ascariandrea]**
- [x] More Or Less #931 **[ascariandrea]**
- [x] NavBar #932 
- [x] Popover #933 
- [x] ResizeSensor #934 **[FrancescoCioria]**
- [x] Scroll #935 
- [x] Tablo #936 **[francescogior]**
- [x] TextOverflow #937 **[ascariandrea]**
- [x] Time Picker #938 **[FrancescoCioria]**
- [x] Toaster #939 **[ascariandrea]**
- [x] Toggle #940
- [x] Transition Wrapper #941 **[ascariandrea]**
- [x] Add npm task to copy file in lib #943 **[ascariandrea]**

**Comment by ascariandrea** [comment]
I've made some research around to discover how other similar libraries structure the `.d.ts` files.
I'm reporting the more significative here:
- [React Toolbox](https://github.com/react-toolbox/react-toolbox/tree/dev/components/app_bar)
- [Semantic-UI-React](https://github.com/Semantic-Org/Semantic-UI-React/tree/master/src/elements/Button)

I noticed the *namespace* strategy is not widely used for similar projects, but I came up with an interesting (IMO) solution:

```ts
import { PureComponent } from 'react'

declare class Divider extends PureComponent<Divider.Props, void> {}

declare namespace Divider {

  type Orientation = 'horizontal' | 'vertical';
  type Size = 'small' | 'medium' | 'large' | 'no-margin';

  export type Props = {
    orientation: Orientation,
    size: Size,
    style: object
  }
}

export = Divider
```

with the above example is possible to

```js
```
